#!/bin/bash
/home/lucasparada20/work/sbrp/scripts/Chicago_20_1.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_20_2.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_30_1.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_30_2.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_40_1.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_40_2.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_50.sh
/home/lucasparada20/work/sbrp/scripts/Chicago_66.sh
/home/lucasparada20/work/sbrp/scripts/Washington_100.sh
/home/lucasparada20/work/sbrp/scripts/Washington_20_1.sh
/home/lucasparada20/work/sbrp/scripts/Washington_20_2.sh
/home/lucasparada20/work/sbrp/scripts/Washington_30_1.sh
/home/lucasparada20/work/sbrp/scripts/Washington_30_2.sh
/home/lucasparada20/work/sbrp/scripts/Washington_40_1.sh
/home/lucasparada20/work/sbrp/scripts/Washington_40_2.sh
/home/lucasparada20/work/sbrp/scripts/Washington_50_1.sh
/home/lucasparada20/work/sbrp/scripts/Washington_50_2.sh
/home/lucasparada20/work/sbrp/scripts/Washington_66.sh
/home/lucasparada20/work/sbrp/scripts/Washington_80_1.sh
/home/lucasparada20/work/sbrp/scripts/Washington_80_2.sh
/home/lucasparada20/work/sbrp/scripts/Washington_90.sh
/home/lucasparada20/work/sbrp/scripts/all_upper_bounds.sh
